Comcast/eel

- config-handlers/tenant1/default.json
- eel/jtl/eventpublisher.go
- eel/jtl/handlers.go
- eel/jtl/nullpublisher.go
> null publisher

- eel/util/http.go
> Update http.go with op keyword

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- util/defaultcontext.go
> XRULES-8388: Panic handling code caused the code to panic

- CHANGELOG.md
- jtl/outproc.go
- XRULES-8923: erroneous metric on published events
@wingdog
> XRULES-8923: erroneous metric

- CHANGELOG.md
- Fixed bad urls in `CHANGELOG.md`
@toyangxia
> Fix compare URLs in CHANGELOG.md

- CHANGELOG.md
- jtl/functions.go
- jtl/jpath.go
- jtl/parser.go
Commented out array_length_error log to address XRULES-9749.
-
-
-
@holidaymike
> Xrules 9749

- CHANGELOG.md
- util/defaultretrier.go
> Update retry to not retry for 300 and 400

- CHANGELOG.md
- jtl/functions.go
- util/config.go
- a new config parameter: ElementsAuth
@xyang200
> Added a new config parameter: ElementsAuth

- CHANGELOG.md
- jtl/eventpublisher.go
- jtl/functions.go
- jtl/handlers.go
- jtl/httppublisher.go
- jtl/jpath.go
- jtl/nullpublisher.go
- jtl/outproc.go
- util/config.go
> Gears suppport

- CHANGELOG.md
- jtl/eventpublisher.go
- jtl/functions.go
- jtl/handlers.go
- jtl/httppublisher.go
- jtl/jpath.go
- jtl/nullpublisher.go
- jtl/outproc.go
- util/config.go
> Revert "Gears suppport"

- CHANGELOG.md
- jtl/eventpublisher.go
- jtl/functions.go
- jtl/handlers.go
- jtl/httppublisher.go
- jtl/jpath.go
- jtl/nullpublisher.go
- jtl/outproc.go
- util/config.go
> Gears support

- jtl/functions.go
- jtl/oauth1.go
> curlOAuth1

- jtl/debughttphandlers.go
- jtl/inproc.go
> rename msg.length to avoid conflict msg as string dictionary in es index

- config-eel/config.json
- jtl/httphandlers.go
- jtl/inproc.go
- jtl/stdinplugin.go
- jtl/workerpool.go
- main.go
- test/eel_test.go
- test/init.go
- util/config.go
- util/stats.go
> XRULES-11240 [Sports Notification] Prevent EEL worker starvation

- CHANGELOG.md
- jtl/workerpool.go
> Reduce log lines

- jtl/outproc.go
> Remove no matching handlers log

- CHANGELOG.md
- jtl/functions.go
- jtl/plugins.go
- main.go
- Add a global flag to disable all plugins except webhook
@xyang200
> Add a global flag to disable all plugins except webhook

- CHANGELOG.md
- jtl/eventpublisher.go
- jtl/handlers.go
XRULES-12168 allow multiple kafka partitions in eel handlers
-
-
-
@wingdog
> allow multiple partitions in array for kafka publisher

- jtl/functions.go
> rename propExists function to propexists

- jtl/jpath.go
XRULES-13169
- [x ] Bug fix (non-breaking change which fixes an issue)
-
-
-
@xyang200
> type check to fix  jtl/jpath.go

- CHANGELOG.md
- jtl/functions.go
- jtl/inproc.go
- jtl/jpath.go
- jtl/stdinplugin.go
- jtl/workerpool.go
- main.go
- util/http.go
> Merge from v1.26 to master

- jtl/inproc.go
> XRULES-11836: Add op keyword in inproc.go log

- CHANGELOG.md
- doc/handlers.md
- jtl/handlers.go
- XRULES-13840: Default handlers in EEL
@xyang200
> XRULES-13840: Default handlers in EEL

- CHANGELOG.md
- jtl/jpath.go
- util/defaultcontext.go
> XRULES-13983: Flow execution log issues

- jtl/handlers.go
XRULES-14298: set tentant id on default handlers
-
-
-
@xyang200
> set correct tenant id for default handlers

- jtl/functions.go
- tenant function will return what's stored in context if it cannot find tenant in the handler
@xyang200
> Make sure the tenant function returns the correct tenant

- jtl/functions.go
- jtl/webhookplugin.go
> Allow webhook to append a apiBasePath if present. Remove oauth1 logic

- CHANGELOG.md
- jtl/functions.go
* XRULES-15127: oauth2get function
@xyang200
> XRULES-15127: oauth2get function

- jtl/functions.go
- jtl/plugins.go
> Fix an issue that sync endpoint no longer does the sync operation

- jtl/functions.go
- jtl/plugins.go
- jtl/webhookplugin.go
> More apiBasePath fun

- jtl/webhookplugin.go
> Added apibasepath to old events

- CHANGELOG.md
- jtl/functions.go
- jtl/handlers.go
> XRULES-16187: Pt 2 - Implement: Isolate flow executions in masheens

- doc/functions.md
- jtl/functions.go
> add stringtojson function

- doc/functions.md
- jtl/functions.go
> add new function for has suffix

- CHANGELOG.md
- config-eel/config.json
- jtl/functions.go
- jtl/inproc.go
- util/config.go
- Logic to handle partner id header for webhook events
-
-
@xyang200
> add logic to handler http partner header

- CHANGELOG.md
- Dockerfile
- doc/functions.md
- jtl/functions.go
- jtl/inproc.go
- test/misc_test.go
- util/config.go
support query string and proxy
- XRULES-20200606: Add function 'param' to read query string parameters of incoming event url
- XRULES-20200606: Add use of HTTP_PROXY environment variable to send data via a proxy
- XRULES-20200606: Docker build; Make smaller runtime image by using multi-stage build, and enable testing
-
@xyang200
@gtrevg 
@holidaymike
> XRULES-20200606: support query string and proxy

- jtl/outproc.go
more debug level logging
-
-
-
@xyang200
> extra debug info when publishing events

- CHANGELOG.md
- util/http.go
> XRULES-19652: panic in nae
